### PR TITLE
Revert "Issue1"

### PR DESCRIPTION
**Pull request by donizk**
Reverts cmpsc-481-s22-m1/ConfiGator#15

### CODE REVIEW

**Comment by kailaniwoodard** [comment]
I have already communicated with Kyrie about this. Approving merge.

**Review by Kevin487 — APPROVED** [review]
Everything looks good! Test cases are showing good coverage and it is showing that the code is working as it should.

**Review by kailaniwoodard — APPROVED** [review]
Looks good! Approving.

**Comment by Michionlion** [comment]
I manually made these changes to `main` so that your history is preserved and future issues are not encountered, so this PR should be closed.

**Pull request closed without merging**
