### PR TITLE
Documentation Overrhaul

### PR DESCRIPTION
**Pull request by kailaniwoodard**
# Proposed Documentation via `README.md` for Release

## Description

Modified `README.md` with addition of `img/icon.png`.

### Type of Change

- [ ] Feature
- [ ] Bug fix
- [X] Documentation

## Contributors

- @kailaniwoodard 

## Reminder

All GitHub Actions should be in a passing state before any pull request is merged.
*Note: Since this branch is pulled from `release/0.1.0`, may not currently be in a passing state.*

### CODE REVIEW

**Review by Kevin487 — APPROVED** [review]
Wow looks amazing! Also, this covers all the requirements mentioned in the reviews by Maria and Seijin.

**Review by TheShiny1 — APPROVED** [review]
A few linting errors still present, but overall very solid.

**Review by connellyw — APPROVED** [review]
Nice formating of the read me

**Comment by kailaniwoodard** [comment]
Fixed all the linting issues, unfortunately unable to add the contributors section but that's so minor that I can revisit it for the final release. Merging.

**Pull request merged**
