### PR TITLE
Issue3

### PR DESCRIPTION
**Pull request by Kevin487**
# Pull Request For Issue3 

## Description

Issue3 is an implementation of the user story "As a... GatorGradle user, I want to...
generate an assignment that uses a specific or latest version of GatorGradle." I have included two test cases that came out with 100% coverage over the code in generate_build_gradle.py. Pylint is also reviewing the code with a score of 10/10. Furthermore, the code will show Generate_build_gradle.py will create a build.gradle file and write strings into. The string that is written will be according to what is assigned by the variable gradlebuild.

### Type of Change

- [x] Feature
- [x] Bug fix
- [x] Documentation

## Contributors

- @Kevin487 

## Reminder

All GitHub Actions should be in a passing state before any pull request is merged.

### CODE REVIEW

**Review by connellyw — DISMISSED** [review]
looks good, ready to merge

**Review by TheShiny1 — DISMISSED** [review]
The test cases look clean and correctly formatted. The test cases look functional with the implementation you provided

**Review by donizk — DISMISSED** [review]
The code and corresponding test cases are organized and seems to successfully generate a build.gradle file.

**Review by Peter-Snipes — DISMISSED** [review]
I looked through your files and they all looked correct. Great job

**Review by connellyw — DISMISSED** [review]
Code changes look good, ready to merge

**Review by TheShiny1 — APPROVED** [review]

**Review by donizk — APPROVED** [review]

**Pull request merged**
