### PR TITLE
Issue 9

### PR DESCRIPTION
**Pull request by kailaniwoodard**
# Issue 9: Generating Default README.md

## Description

Generating a default README.md based off a template

### Type of Change

- [x] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @kailaniwoodard 

## Reminder

All GitHub Actions should be in a passing state before any pull request is merged.

### CODE REVIEW

**Review by donizk — DISMISSED** [review]
Looks good!

**Review by Kevin487 — DISMISSED** [review]
Hey! This READ.ME looks good, from my understanding of a READ.ME, and is ready for approval.

**Review by Kevin487 — DISMISSED** [review]
This READ.ME looks good, from my understanding of the requirements! This is ready for approval!

**Review by Kevin487 — APPROVED** [review]
This READ.ME looks good! linting is passing and coverage from the successful test is showing that the code is working as it should.

**Review by mariakimheinert — APPROVED** [review]
Although I haven't reviewed these changes in-depth, they look good enough to merge into `develop` for inclusion in the release candidate, where they will be reviewed further.

**Pull request merged**
