### PR TITLE
Issue1

### PR DESCRIPTION
**Pull request by donizk**
# Issue 1: gatorgrader.yml config file generator

## Description

In this pull request, we have a program that creates a gatorgrader.yml file that is nested in a directory called config. This program also has corresponding test cases that tests that a GatorGradle run fails if a single checks fail based on the config file generated and that a directory called config is created.

### Type of Change

- [x] Feature
- [ ] Bug fix
- [x] Documentation

## Contributors

- @TheShiny1 
- @donizk 

## Reminder

All GitHub Actions should be in a passing state before any pull request is merged.

### CODE REVIEW

**Review by kailaniwoodard — DISMISSED** [review]
Looks good! Giving approval.

**Review by Kevin487 — DISMISSED** [review]
Everything looks good for this issue! test cases are showing good coverage, which shows the code is working as it should.

**Review by Kevin487 — APPROVED** [review]
Everything looks good because it is the same code I saw from before. Test cases show good coverage through mock, which shows the code is working as it should.

**Review by kailaniwoodard — APPROVED** [review]
Changes are minimal, all looks good. Approving.

**Pull request merged**
